### ISSUE TITLE
MVP Website

### ISSUE THREAD

**Issue by mkristiansen** [LastHopeAnimalCharity/planning#12]
**As a** WebSite Administrator 
**I want** a manually created, static website publishing through gh_pages to a preview version on a subdomain of github.io
**So that** I review and develop the solution in agile, incremental deliverables

**Comment by mkristiansen** [comment]
Was there a specific need to call the repo LastHopeAnimalCharity.github.io? 
Since the published website will (eventually) end up on lasthope.ie I would like the preview site to be named lasthope-preview.github.io. If it's too hard to change in the middle of your current activity we can keep it for the evaluation/early exploration phase and migrate over subsequently.

**Comment by mkristiansen** [comment]
Also notice I have changed the goal posts - reduced them to focus on just publishing a manually created static website. In a new story we will fold in gatsby.js rendered static site.

**Comment by Gosiaisean** [comment]
As stated on the githubpage "Head over to GitHub and create a new repository **named** **username**.github.io, where u**sername is your username (or organization name) on GitHub**.
If the first part of the repository d**oesn’t exactly match your username, it won’t work**, so make sure to get it right."
Later on we can change it ti custom domiain as described in https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by mkristiansen** [comment]
Got it. We dont want to pay for a DNS name for the preview version of the site... No need to worry about it for now - I'll add a story to capture this req. Continue as you are.

**Comment by mkristiansen** [comment]
Finished
