### ISSUE TITLE
Deploy sample side to netlify

### ISSUE THREAD

**Issue by Gosiaisean** [LastHopeAnimalCharity/planning#17]
https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/
https://www.netlify.com/blog/2016/02/24/a-step-by-step-guide-gatsby-on-netlify/

**Comment by mkristiansen** [comment]
@Gosiaisean as we discussed we should not deploy to netlify.. should this task be closed as obsolete? If not please update, if yes - which task are you working off currently.

**Comment by Gosiaisean** [comment]
closing.
working on https://github.com/LastHopeAnimalCharity/planning/issues/12
