### ISSUE TITLE
mark down component spike

### ISSUE THREAD

**Issue by mandie12** [LastHopeAnimalCharity/planning#9]
As a WebSite Administrator
I want to add some content using markdown editor on gh_pages 
This will automatically update content on to the website

**Comment by mkristiansen** [comment]
@mandie12 
Starting with this one.. could we please ensure each task documents at high level what is required to mark complete. ie basic acceptance criteria

**Comment by mandie12** [comment]
@mkristiansen please correct if you believe this is the wrong description

**Comment by mkristiansen** [comment]
Thanks, that looks reasonable.
If you want to stick to agile user stories for technical tasks that's perfectly fine but if you prefer other formats that's ok too.

**Comment by mkristiansen** [comment]
Closing as duplicate of #12. Verified with @Gosiaisean that edits to markdown content on gh automatically pushes to the site.
